### ISSUE TITLE
Home page style/formatting

### ISSUE THREAD

**Issue by leina05** [thayer/dfr#12]
A few stylistic things:
- Personal preference, but I think the logo looks better on black and it would be great if we could change the index bar to be black/charcoal (like the GitHub index bar actually). We could make the Donate button green. 
- I think that the font of the blurb on the homepage should be one or two sizes larger 
- The font in the footer should be all the same font size (the smallest of the sizes currently used). Also @ALowVerus, you should make your name a lighter green or gray because it's difficult to see agains the background color. 
- It would be nice to see more of the car in the picture. I like the idea of the learn more button, but maybe we could move the title and the button below the picture or above the picture, or in some way keep it from blocking the car.

**Comment by ALowVerus** [comment]
Fixed index and donate colors.

**Comment by ALowVerus** [comment]
Not sure what you mean by the "blurb". Could you copy and paste the text here to confirm?

**Comment by ALowVerus** [comment]
Fixed name color.

**Comment by ALowVerus** [comment]
Reduced footer text size.

**Comment by ALowVerus** [comment]
Not sure what you mean by "Not blocking car". I can't track the median area of the car: I can float text to the top / bottom / left / right / middle. Is this what you're looking for? Floated to the top?
![screenshot from 2018-12-15 10-42-32](https://user-images.githubusercontent.com/18432352/50044738-2cc7f480-0056-11e9-85f4-510f061528b5.png)

**Comment by leina05** [comment]
Colors look great! I like floated to the top. 

The blurb is: 
Dartmouth Formula Racing (DFR) is an entirely student-run organization at Dartmouth College's Thayer School of Engineering. Since 1995, our team has designed and produced award winning formula racecars to compete against other teams from across the country. The DFR team designs, manufactures, assembles, tests, and drives open-wheeled racecars to compete in the Formula Hybrid Competition held by the Formula Society of Automotive Engineers (FSAE) each May.
