### ISSUE TITLE
Sponsor Page

### ISSUE THREAD

**Issue by benschneider8** [thayer/dfr#6]
I don't think we should have the sponsor dollar amount or list the benefits. Just the level and logo. 

However, it would be cool if we could have a pdf copy of the sponsorship packet linked on the page so people could download and look at it there

**Comment by ALowVerus** [comment]
I don't see that. In "thayerfs/common/dfr/2019%20DFR/Finances%20&%20Sponsorship/" there is a word document called BROCHUREFINAL.docx which I do not have permission to open and another called DFRSPONSORSHIPINFO.pdf which reads errors every time I try to open it. Could you just send me the file over Slack?

**Comment by ALowVerus** [comment]
Fixed.
